version: '3.8'

services:
  backend_container:
    build: ./backend
    container_name: backend_container
    ports:
      - "4000:4000"

  frontend_container:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend_container