name: WACAD017 - LP01 - Compilacao via Push

on:
  push:
    branches:
      - main
    paths:
      - "WACAD017 - Fundamentos de Integração Contínua - T7/LP01/**"
      - ".github/workflows/wacad017-lp01-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v7

      - name: Instalar compilador
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Compilar programa
        run: |
          gcc "WACAD017 - Fundamentos de Integração Contínua - T7/LP01/compilacao/main.c" -o programa

      - name: Executar programa compilado
        run: ./programa
