name: Simple Local

on:
  push:
    paths:
      - "WACAD017 - Fundamentos de Integração Contínua - T7/LP02/app.js"
      - "WACAD017 - Fundamentos de Integração Contínua - T7/LP02/package.json"
      - "WACAD017 - Fundamentos de Integração Contínua - T7/LP02/package-lock.json"
      - ".github/workflows/wacad017-lp02-simple-local.yml"

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Verificar versao do Node
        run: node --version

      - name: Verificar versao do npm
        run: npm --version

      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          cd "WACAD017 - Fundamentos de Integração Contínua - T7/LP02"
          npm install

      - name: Instalar Moment
        run: |
          cd "WACAD017 - Fundamentos de Integração Contínua - T7/LP02"
          npm install --save moment

      - name: Executar aplicacao
        run: |
          cd "WACAD017 - Fundamentos de Integração Contínua - T7/LP02"
          node app.js
